Completed node-fs-readfile
Johnny-Baltazar/m2-0122-code-solutions pull request #22
Opened 2022-03-07 22:35 UTC by Johnny-Baltazar

![level-1](https://user-images.githubusercontent.com/25161542/157129484-8f3c97a8-e15b-45b2-9c02-149fa7bc5720.png)
![level-2](https://user-images.githubusercontent.com/25161542/157129490-637d38f7-b83e-447e-afae-2431aee3e246.png)

2022-03-08 02:11 UTC, TimelikeClosure requested changes

2022-03-08 02:11 UTC, TimelikeClosure commented on node-fs-readfile/read-any.js
> +}
This should work for _any_ file name, not just the files you know are there.

2022-03-08 16:26 UTC, Johnny-Baltazar commented
![Screenshot 2022-03-08 082328](https://user-images.githubusercontent.com/25161542/157280960-be28cdd1-a34e-4c81-8960-99895942dce0.png)

2022-03-09 02:29 UTC, TimelikeClosure approved these changes

2022-03-09 03:27 UTC, merged