Completed javascript-bank
Johnny-Baltazar/m2-0122-code-solutions pull request #6
Opened 2022-01-31 20:42 UTC by Johnny-Baltazar

![javascript-bank](https://user-images.githubusercontent.com/25161542/151869913-a69fd984-58ff-477d-96fe-a030c1eba012.gif)

2022-02-01 02:46 UTC, TimelikeClosure requested changes

2022-02-01 02:46 UTC, TimelikeClosure commented on javascript-bank/account.js
> +    );
The `Transaction` constructor takes the `type` and `amount` as _arguments_, meaning you don't need to assign them to `this.anything`. In fact, on lines 12-13, `this` refers to the current `Account` object, not the `Transaction` object you're  creating.

---

![image](https://user-images.githubusercontent.com/16143771/151905468-1559d792-560b-43dd-a238-f99e3ecbe04e.png)

2022-02-01 02:46 UTC, TimelikeClosure commented on javascript-bank/bank.js
> +    );
Like the comment above, `this` refers to the new `Bank` object here, not the `Account` object being created.

2022-02-02 03:31 UTC, Johnny-Baltazar commented
![js bank](https://user-images.githubusercontent.com/25161542/152088944-735a4ff1-1f4d-4aef-9d55-36aadda1f365.gif)

2022-02-02 03:33 UTC, TimelikeClosure approved these changes

2022-02-02 03:38 UTC, merged